language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

notifications:
  email:
    recipients:
      - ricardomachado.sb@gmail.com
      - florescmichele@gmail.com
      - felipeghiggi92@gmail.com
    on_success: always # default: change
    on_failure: always # default: always