language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

notifications:
  email:
    recipients:
      - ricardomachado.sb@gmail.com
      - florescmichele@gmail.com 
      - felipeghiggi92@gmail.com 
      - mtsaeu@gmail.com 
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always